### ISSUE TITLE
This is a very good plug-in!  Is there any way to convert the synthesized morph into a DSF file available for DAZ3D?

### ISSUE THREAD

**Issue by wenxiao2012** [ProjectCanyon/morph-merger#5]
This is a very good plug-in!  Is there any way to convert the synthesized morph into a DSF file available for DAZ3D?

**Comment by chokaphi** [comment]
https://www.reddit.com/r/VAMscenes/comments/dro2c3/vam_to_daz_a_utility_to_convert_vam_vmb_back_to/

**Comment by ProjectCanyon** [comment]
Hi, yeah it's going to be better to go with the above for the time being, MorphMerger uses the interpreted morphs loading in from the VaM code. By the time we are merging them they are different enough from the original morphs that trying to save them back to Daz format would require quite a bit of work. Thanks for your feedback though!
